name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-all-crates:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          # thanks to this it shoun't mix affects from different types of Rust
          key: ${{ runner.os }}-cargo-target-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}


      - name: Run Rust fmt check
        run: cargo fmt --all -- --check

      # it use single manifest root `Cargo.toml`
      - name: Build all crates
        run: cargo build --all --verbose

      # it use single manifest root `Cargo.toml`
      - name: Test all crates
        run: cargo test --all --verbose

